# Generated by Django 3.1.2 on 2021-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=120)),
                ('addess', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
        ),
    ]
