# Generated by Django 3.1.7 on 2021-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=150)),
                ('desc2', models.CharField(max_length=150)),
                ('img', models.ImageField(default='', upload_to='adout')),
                ('date', models.DateField()),
            ],
        ),
    ]
