# Generated by Django 3.1.7 on 2021-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocktitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocktitle', models.CharField(max_length=100)),
                ('blockdesc', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='blockdesc',
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocktitle',
        ),
    ]
