# Generated by Django 3.1.7 on 2021-03-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210308_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='Blog',
        ),
    ]
