# Generated by Django 3.1.7 on 2021-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='newsletter',
        ),
    ]
