# Generated by Django 3.1.7 on 2021-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210309_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='newsletter',
            new_name='newsletteremail',
        ),
    ]
